### ISSUE TITLE
Problem installing torchseq

### ISSUE THREAD

**Issue by halakhah** [tomhosking/torchseq#2]
Hiya, 

I'll leave this on the torchseq repository as well. 

When I run 

`python3 -m pip install git+https://github.com/tomhosking/torchseq.git@v2.3.1`

via terminal, I get this issue

```
Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [32 lines of output]
      Traceback (most recent call last):
        File "/Users/voi/Library/Python/3.8/lib/python/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/Users/voi/Library/Python/3.8/lib/python/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/voi/Library/Python/3.8/lib/python/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/build_meta.py", line 146, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/build_meta.py", line 127, in _get_build_requires
          self.run_setup()
        File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/build_meta.py", line 142, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 7, in <module>
          setup(
        File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/__init__.py", line 165, in setup
          return distutils.core.setup(**attrs)
        File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 108, in setup
          _setup_distribution = dist = klass(attrs)
        File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/dist.py", line 429, in __init__
          _Distribution.__init__(self, {
        File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 293, in __init__
          self.finalize_options()
        File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/dist.py", line 721, in finalize_options
          ep(self)
        File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/dist.py", line 727, in _finalize_setup_keywords
          ep.require(installer=self.fetch_build_egg)
        File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2483, in require
          items = working_set.resolve(reqs, env, installer, extras=self.extras)
        File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 790, in resolve
          raise VersionConflict(dist, req).with_context(dependent_req)
      pkg_resources.VersionConflict: (setuptools 49.2.1 (/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages), Requirement.parse('setuptools>=58.0'))
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by tomhosking** [comment]
Hi, could you let me know what version of python and pip you're using?

**Comment by halakhah** [comment]
> Hi, could you let me know what version of python and pip you're using?

Python 3.8.9

and

pip 22.1.2 from /Users/voi/Library/Python/3.8/lib/python/site-packages/pip (python 3.8)

**Comment by tomhosking** [comment]
I've just created a fresh virtualenv on python 3.8.5, installed pip==22.1.2 and successfully installed torchseq. It looks like you're installing into the global python install and it's causing a version conflict, have you tried installing to a virtualenv?
```
python3 -m venv torchseqenv
source torchseqenv/bin/activate
pip install --upgrade pip
pip install git+https://github.com/tomhosking/torchseq.git@v2.3.1
```

**Comment by halakhah** [comment]
Thanks for the help. That worked, except now I'm getting a similar issue for tokenizers.

```
Building wheel for tokenizers (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for tokenizers (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [51 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-10.14.6-arm64-cpython-38
      creating build/lib.macosx-10.14.6-arm64-cpython-38/tokenizers
      copying py_src/tokenizers/__init__.py -> build/lib.macosx-10.14.6-arm64-cpython-38/tokenizers
      creating build/lib.macosx-10.14.6-arm64-cpython-38/tokenizers/models
      copying py_src/tokenizers/models/__init__.py -> build/lib.macosx-10.14.6-arm64-cpython-38/tokenizers/models
      creating build/lib.macosx-10.14.6-arm64-cpython-38/tokenizers/decoders
      copying py_src/tokenizers/decoders/__init__.py -> build/lib.macosx-10.14.6-arm64-cpython-38/tokenizers/decoders
      creating build/lib.macosx-10.14.6-arm64-cpython-38/tokenizers/normalizers
      copying py_src/tokenizers/normalizers/__init__.py -> build/lib.macosx-10.14.6-arm64-cpython-38/tokenizers/normalizers
      creating build/lib.macosx-10.14.6-arm64-cpython-38/tokenizers/pre_tokenizers
      copying py_src/tokenizers/pre_tokenizers/__init__.py -> build/lib.macosx-10.14.6-arm64-cpython-38/tokenizers/pre_tokenizers
      creating build/lib.macosx-10.14.6-arm64-cpython-38/tokenizers/processors
      copying py_src/tokenizers/processors/__init__.py -> build/lib.macosx-10.14.6-arm64-cpython-38/tokenizers/processors
      creating build/lib.macosx-10.14.6-arm64-cpython-38/tokenizers/trainers
      copying py_src/tokenizers/trainers/__init__.py -> build/lib.macosx-10.14.6-arm64-cpython-38/tokenizers/trainers
      creating build/lib.macosx-10.14.6-arm64-cpython-38/tokenizers/implementations
      copying py_src/tokenizers/implementations/byte_level_bpe.py -> build/lib.macosx-10.14.6-arm64-cpython-38/tokenizers/implementations
      copying py_src/tokenizers/implementations/sentencepiece_unigram.py -> build/lib.macosx-10.14.6-arm64-cpython-38/tokenizers/implementations
      copying py_src/tokenizers/implementations/sentencepiece_bpe.py -> build/lib.macosx-10.14.6-arm64-cpython-38/tokenizers/implementations
      copying py_src/tokenizers/implementations/base_tokenizer.py -> build/lib.macosx-10.14.6-arm64-cpython-38/tokenizers/implementations
      copying py_src/tokenizers/implementations/__init__.py -> build/lib.macosx-10.14.6-arm64-cpython-38/tokenizers/implementations
      copying py_src/tokenizers/implementations/char_level_bpe.py -> build/lib.macosx-10.14.6-arm64-cpython-38/tokenizers/implementations
      copying py_src/tokenizers/implementations/bert_wordpiece.py -> build/lib.macosx-10.14.6-arm64-cpython-38/tokenizers/implementations
      creating build/lib.macosx-10.14.6-arm64-cpython-38/tokenizers/tools
      copying py_src/tokenizers/tools/__init__.py -> build/lib.macosx-10.14.6-arm64-cpython-38/tokenizers/tools
      copying py_src/tokenizers/tools/visualizer.py -> build/lib.macosx-10.14.6-arm64-cpython-38/tokenizers/tools
      copying py_src/tokenizers/__init__.pyi -> build/lib.macosx-10.14.6-arm64-cpython-38/tokenizers
      copying py_src/tokenizers/models/__init__.pyi -> build/lib.macosx-10.14.6-arm64-cpython-38/tokenizers/models
      copying py_src/tokenizers/decoders/__init__.pyi -> build/lib.macosx-10.14.6-arm64-cpython-38/tokenizers/decoders
      copying py_src/tokenizers/normalizers/__init__.pyi -> build/lib.macosx-10.14.6-arm64-cpython-38/tokenizers/normalizers
      copying py_src/tokenizers/pre_tokenizers/__init__.pyi -> build/lib.macosx-10.14.6-arm64-cpython-38/tokenizers/pre_tokenizers
      copying py_src/tokenizers/processors/__init__.pyi -> build/lib.macosx-10.14.6-arm64-cpython-38/tokenizers/processors
      copying py_src/tokenizers/trainers/__init__.pyi -> build/lib.macosx-10.14.6-arm64-cpython-38/tokenizers/trainers
      copying py_src/tokenizers/tools/visualizer-styles.css -> build/lib.macosx-10.14.6-arm64-cpython-38/tokenizers/tools
      running build_ext
      running build_rust
      error: can't find Rust compiler
      
      If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler.
      
      To update pip, run:
      
          pip install --upgrade pip
      
      and then retry package installation.
      
      If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs) is the recommended way to download and update the Rust compiler toolchain.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for tokenizers
  Building wheel for psutil (pyproject.toml) ... done
  Created wheel for psutil: filename=psutil-5.9.1-cp38-cp38-macosx_10_14_arm64.whl size=265091 sha256=2786dab30b90b076879385103ec3477a2c0587abd7a911acd017a2517a44985d
  Stored in directory: /Users/voi/Library/Caches/pip/wheels/69/3f/b4/d3ed6919124e311eab9e7b9a264f31fd43ae8e7241d4611228
  Building wheel for pyyaml (pyproject.toml) ... done
  Created wheel for pyyaml: filename=PyYAML-6.0-cp38-cp38-macosx_10_14_arm64.whl size=45338 sha256=e28fc1e7431cbab68922680ac476355084eb6ab3695068758d5018309bc18a3b
  Stored in directory: /Users/voi/Library/Caches/pip/wheels/52/84/66/50912fd7bf1639a31758e40bd4312602e104a8eca1e0da9645
Successfully built psutil pyyaml
Failed to build tokenizers
ERROR: Could not build wheels for tokenizers, which is required to install pyproject.toml-based projects
```

**Comment by halakhah** [comment]
Hopefully fixed this issue. Trying it out now. Hit a snag at building the wheel for tokenizers, as it's taking a while via terminal.

**Comment by tomhosking** [comment]
There should usually be a prebuilt wheel for `tokenizers` - it may be that one isn't available for mac, or for your version of macos?

**Comment by tomhosking** [comment]
If you don't have a GPU, you can set `--cpu` on the command line, or pass `use_cuda=False` as a parameter when constructing the `ParaphrasingAgent` object.

**Comment by halakhah** [comment]
I really appreciate you walking me through this. 

I edited the code to include that parameter, and after running it again I got

```
Some unexpected keys were found in the loaded checkpoint: 
seq_encoder.embedding_projection.weight_g
seq_encoder.embedding_projection.weight_v
bottleneck.module_list.1.quantizer._alpha
bottleneck.module_list.1.quantizer._ema_cluster_size0
bottleneck.module_list.1.quantizer._ema_cluster_size1
bottleneck.module_list.1.quantizer._ema_cluster_size2
bottleneck.module_list.1.quantizer._ema_w.0
bottleneck.module_list.1.quantizer._ema_w.1
bottleneck.module_list.1.quantizer._ema_w.2
Validating after 12 epochs:   0%|                         | 0/1 [00:00<?, ?it/s]Some unexpected keys were found in the loaded checkpoint: 
seq_encoder.embedding_projection.weight_g
seq_encoder.embedding_projection.weight_v
bottleneck.module_list.1.quantizer._alpha
bottleneck.module_list.1.quantizer._ema_cluster_size0
bottleneck.module_list.1.quantizer._ema_cluster_size1
bottleneck.module_list.1.quantizer._ema_cluster_size2
bottleneck.module_list.1.quantizer._ema_w.0
bottleneck.module_list.1.quantizer._ema_w.1
bottleneck.module_list.1.quantizer._ema_w.2
Some unexpected keys were found in the loaded checkpoint: 
seq_encoder.embedding_projection.weight_g
seq_encoder.embedding_projection.weight_v
bottleneck.module_list.1.quantizer._alpha
bottleneck.module_list.1.quantizer._ema_cluster_size0
bottleneck.module_list.1.quantizer._ema_cluster_size1
bottleneck.module_list.1.quantizer._ema_cluster_size2
bottleneck.module_list.1.quantizer._ema_w.0
bottleneck.module_list.1.quantizer._ema_w.1
bottleneck.module_list.1.quantizer._ema_w.2
Validating after 12 epochs:   0%|                         | 0/1 [00:00<?, ?it/s]
Validating after 12 epochs:   0%|                         | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    exitcode = _main(fd, parent_sentinel)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    prepare(preparation_data)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 265, in run_path
    main_content = runpy.run_path(main_path,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 97, in _run_module_code
    return _run_module_code(code, init_globals, run_name,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    _run_code(code, mod_globals, init_globals,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/voi/test2", line 83, in <module>
    exec(code, run_globals)
  File "/Users/voi/test2", line 83, in <module>
    _, _, (_, _, _), memory_eval = agent.inference(
  File "/Users/voi/torchseqenv/lib/python3.8/site-packages/torchseq/agents/model_agent.py", line 554, in inference
    _, _, (_, _, _), memory_eval = agent.inference(
  File "/Users/voi/torchseqenv/lib/python3.8/site-packages/torchseq/agents/model_agent.py", line 554, in inference
    for batch_idx, batch in enumerate(
  File "/Users/voi/torchseqenv/lib/python3.8/site-packages/tqdm/std.py", line 1195, in __iter__
    for batch_idx, batch in enumerate(
  File "/Users/voi/torchseqenv/lib/python3.8/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/Users/voi/torchseqenv/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 359, in __iter__
    for obj in iterable:
  File "/Users/voi/torchseqenv/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 359, in __iter__
    return self._get_iterator()
  File "/Users/voi/torchseqenv/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 305, in _get_iterator
    return self._get_iterator()
  File "/Users/voi/torchseqenv/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 305, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/Users/voi/torchseqenv/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 918, in __init__
    return _MultiProcessingDataLoaderIter(self)
  File "/Users/voi/torchseqenv/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 918, in __init__
    w.start()
    w.start()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 121, in start
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    self._popen = self._Popen(self)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    return Popen(process_obj)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    super().__init__(process_obj)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
    self._launch(process_obj)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 154, in get_preparation_data
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
    _check_not_importing_main()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

Validating after 12 epochs:   0%|                         | 0/1 [00:03<?, ?it/s]
Traceback (most recent call last):
  File "/Users/voi/torchseqenv/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 990, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/queues.py", line 107, in get
    if not self._poll(timeout):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/connection.py", line 424, in _poll
    r = wait([self], timeout)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/connection.py", line 931, in wait
    ready = selector.select(timeout)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
  File "/Users/voi/torchseqenv/lib/python3.8/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 25567) exited unexpectedly with exit code 1. Details are lost due to multiprocessing. Rerunning with num_workers=0 may give better error trace.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test2", line 83, in <module>
    _, _, (_, _, _), memory_eval = agent.inference(
  File "/Users/voi/torchseqenv/lib/python3.8/site-packages/torchseq/agents/model_agent.py", line 554, in inference
    for batch_idx, batch in enumerate(
  File "/Users/voi/torchseqenv/lib/python3.8/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/Users/voi/torchseqenv/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/Users/voi/torchseqenv/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1186, in _next_data
    idx, data = self._get_data()
  File "/Users/voi/torchseqenv/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1152, in _get_data
    success, data = self._try_get_data()
  File "/Users/voi/torchseqenv/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1003, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 25567, 25568) exited unexpectedly
```

**Comment by tomhosking** [comment]
How are you running the code? You may need to add a "if guard" to your main script file, see these pages:
https://discuss.pytorch.org/t/runtimeerror-an-attempt-has-been-made-to-start-a-new-process-before-the-current-process-has-finished-its-bootstrapping-phase/145462
https://pytorch.org/docs/stable/notes/windows.html#multiprocessing-error-without-if-clause-protection

**Comment by tomhosking** [comment]
(You can ignore the messages about unexpected keys in the checkpoints - these were unused variables that got removed from the code after I trained the models)

**Comment by halakhah** [comment]
Alright, that helped. Now, I'm getting 

`Exception: Tokenizer needs to be initialized with a model name before use!`

**Comment by halakhah** [comment]
```
def main():    
    # Which checkpoint should we load?
    path_to_model = '/Users/voi/Downloads/hrq-vae-main/models/hrqvae_paralex'

    # .Path to datasets+vocabs
    DATA_PATH = '/Users/voi/Downloads/hrq-vae-main/data/'


    # What are the inputs?
    examples = [
        {'sem_input': 'Alexa please turn on the television.'},
        {'sem_input': 'Siri what is the weather like outside today'},
        {'sem_input': 'I am excited to see what this movie is about, but I have heard bad reviews.'},
        {'sem_input': 'Miriam said that she went to the gym, and she needs to rest for a little
bit.'},
        {'sem_input': 'When I went to the store, an employee told me that they were out of almond milk, but I found some in the dairy aisle anyway.'},
        {'sem_input': 'I am really busy today, and I do not have the time to clean up the garage; would you mind helping me out by tidying up the garage for me?'},
        {'sem_input': 'The basic goal is to find algebraic invariants that classify topological spaces up to homeomorphism, though usually most classify up to homotopy equivalence.'}]

    # How many paraphrases to generate?
    top_k = 3

    # **** You shouldn't need to change anything below here ****

    # Generating multiple paraphrases from the model is a little complicated 
    # and requires more than one step:
    # First, we need to get z_sem for the inputs. 
    # Then, we sample multiple sketches {q_i} from the code prediction 
    # network.
    # Finally, we run the decoder using each sketch and z_sem as input

    import json, jsonlines, sacrebleu, logging, copy
    from tqdm import tqdm
    from torchseq.agents.para_agent import ParaphraseAgent
    from torchseq.datasets.json_loader import JsonDataLoader
    from torchseq.utils.config import Config

    import torch

    # Create the dataset and model
    with open(path_to_model + "/config.json") as f:
        cfg_dict = json.load(f)

    logger = logging.getLogger('TorchSeq')

    config = Config(cfg_dict)
    checkpoint_path = path_to_model + "/model/checkpoint.pt"
    agent = ParaphraseAgent(config=config, run_id=None,  output_path=None, 
    data_path=DATA_PATH, silent=False, verbose=False, training_mode=False, 
    use_cuda=False)

    # Load the checkpoint
    agent.load_checkpoint(checkpoint_path)
    agent.model.eval()


    # Generate encodings
    logger.info("Generating encodings for eval set")
    config_gen_eval = copy.deepcopy(config.data)
    config_gen_eval["dataset"] = "json"
    config_gen_eval["json_dataset"] = {
        "path": config.eval.metrics.sep_ae.eval_dataset,
        "field_map": [
            {"type": "copy", "from": "sem_input", "to": "s2"},
            {"type": "copy", "from": "sem_input", "to": "template"},
            {"type": "copy", "from": "sem_input", "to": "s1"},
        ],
    }
    config_gen_eval["eval"]["topk"] = 1

    data_loader = JsonDataLoader(
        data_path=agent.data_path,
        config=Config(config_gen_eval),
        dev_samples=examples,
    )

    config.eval.data["sample_outputs"] = False

    post_bottleneck = (
        "_after_bottleneck" if 
    agent.config.bottleneck.code_predictor.get("post_bottleneck", False) else 
    ""
    )

    _, _, (_, _, _), memory_eval = agent.inference(
        data_loader.valid_loader,
        memory_keys_to_return=[f"sep_encoding_1{post_bottleneck}", 
    f"sep_encoding_2{post_bottleneck}", "vq_codes"],
    )

    if not agent.config.bottleneck.code_predictor.get("sem_only", False):
        X_eval = torch.cat(
            [
                memory_eval[f"sep_encoding_1{post_bottleneck}"][:, 0, :],
                memory_eval[f"sep_encoding_2{post_bottleneck}"][:, 0, :],
            ],
            dim=1,
        )
    else:
        X_eval = memory_eval[f"sep_encoding_1{post_bottleneck}"][:, 0, :]
    y_eval = memory_eval["vq_codes"]

    # Get top-k predicted codes

    logger.info("Running code predictor")

    if agent.model.code_predictor.config.get("beam_width", 0) < top_k:
        agent.model.code_predictor.config.data["beam_width"] = top_k

    pred_codes = []
    # # TODO: batchify!
    for ix, x_batch in enumerate(tqdm(X_eval, desc="Predicting codes")):
        curr_codes = agent.model.code_predictor.infer(
            x_batch.unsqueeze(0).to(agent.device), {}, 
    outputs_to_block=y_eval[ix].unsqueeze(0), top_k=top_k
        )
        pred_codes.append(curr_codes)


    pred_codes = torch.cat(pred_codes, dim=0)

    config_pred_diversity = copy.deepcopy(config.data)
    config_pred_diversity["dataset"] = "json"
    config_pred_diversity["json_dataset"] = {
        "path": config.eval.metrics.sep_ae.eval_dataset,
        "field_map": [
            {"type": "copy", "from": "sem_input", "to": "s2"},
            {"type": "copy", "from": "sem_input", "to": "template"},
            {"type": "copy", "from": "sem_input", "to": "s1"},
            {"type": "copy", "from": "forced_codes", "to": "forced_codes"},
        ],
    }
    config_pred_diversity["eval"]["topk"] = 1

    data_loader = JsonDataLoader(
        data_path=agent.data_path,
        config=Config(config_pred_diversity),
        dev_samples=examples,
    )

    config.eval.data["sample_outputs"] = True

    topk_outputs = []

    for k in range(top_k):
        logger.info(f"Running generation with {k+1}th best codes")

        samples = data_loader._valid.samples
        samples = [{**x, "forced_codes": pred_codes[i, k, :].tolist()} for i, 
    x in enumerate(samples)]
        forced_loader = JsonDataLoader(
            data_path=agent.data_path, config=Config(config_pred_diversity), 
    dev_samples=samples
        )

        _, _, (output, _, _), _ = agent.inference(forced_loader.valid_loader)


        topk_outputs.append(output)


    print(topk_outputs)
    
if __name__ == '__main__':
    main()
```

**Comment by halakhah** [comment]
Okay, that's a bummer! But I really, really appreciate your help. And thank you for the information and working the script on my examples; that actually resolves the need to work with the script, as I'm looking for something that works with commands and general sentences.
